### ISSUE TITLE
RSS Feed is down

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [sanjoy/playingwithpointers.com#3]
All RSS addresses I know are down. Impossible to access them:

- http://playingwithpointers.com/feed.rss
- http://playingwithpointers.com/feed.xml

I would also like to mention that they are very difficult to find as they are not mentioned in the html head section ;)

**Comment by sanjoy** [comment]
http://playingwithpointers.com/feed.xml works for me.  And feed.rss should redirect to feed.xml.

I'll try to figure out how to make this more visible, though; thanks for the feedback!

**Comment by DEKHTIARJonathan** [comment]
Indeed I don't know why it was down last time I checked.

If it can help, this is how I solve this:

```
<link href="/feed_atom.xml" type="application/atom+xml" rel="alternate" title="Born2Data Full Atom Feed">
<link href="/feed_rss.xml" type="application/rss+xml" rel="alternate" title="Born2Data Full RSS Feed">
```

This indicates RSS Readers and Browsers that an RSS Feed and an Atom Feeds are available for this webpage ;)
